export const types = {
  REMOVE_FROM_USER: "REMOVE_FROM_USER",
  CREATE_DIVING_SPOT: "CREATE_DIVING_SPOT",
  ADD_TO_USER: "ADD_TO_USER",
  FETCH_DIVING_SPOT_SELECTOR: "FETCH_DIVING_SPOT_SELECTOR",
};
