export const types = {
  FETCH_MONTHLY_DIVE: "FETCH_MONTHLY_DIVE",
  FETCH_MOST_REPORTED_SPECIES: "FETCH_MOST_REPORTED_SPECIES",
  FETCH_RANKING_DIVES: "FETCH_RANKING_DIVES",
  FETCH_DIVE_CREATURES: "FETCH_DIVE_CREATURES",
  FETCH_DIVE_COORDS: "FETCH_DIVE_COORDS",
  FETCH_DIVE: "FETCH_DIVE",
  FETCH_SPECIES_DIVES: "FETCH_SPECIES_DIVES",
  DELETE_DIVE: "DELETE_DIVE",
};
